# URL de Producción (Recomendado usar variables de entorno)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
# 'none' asegura que el código no toque la estructura de la BD bajo ninguna circunstancia
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Pool de conexiones (Optimización para muchos usuarios)
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5