# URL de la base de datos de QA
spring.datasource.url=jdbc:postgresql://servidor-qa:5432/nombre_tu_bd_qa
spring.datasource.username=usuario_qa
spring.datasource.password=clave_qa_segura

# JPA / Hibernate
# 'validate' solo comprueba que las tablas existan; si falta algo, la app no arranca (evita errores en test)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Logs un poco más limpios
logging.level.org.hibernate.SQL=info